### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by robertrico** [TheParrotsAreComing/PAWS#10]
When adding a cat, I was unable to add a cat without dates. ( DOB and Microchip )

However, the system did not tell me what is going on.

I left some code to get error reporting started.

"Required" on the DOB Month.
And Implemented the "Flash Message" 

Note: The flash message needs to be styled.

**Comment by theRonLewis** [comment]
Required field stars have been added to all fields on all forms to lay the foundation for at least indicating required fields to the user. This will have to be evaluated by each pair for their feature, although Charisse sounded pretty adamant about making all fields required (will probably need to check on certain things, like I'm not sure if the adoption fee or chip# needs to/can be be required - if the adoption fee is what the adopter actually pays then it is found out later, if the kittens are newborns, they won't be able to get microchips at all for X number of weeks).
