### ISSUE TITLE
ETA on Litters

### ISSUE THREAD

**Issue by robertrico** [TheParrotsAreComing/PAWS#33]
Move ETA on litters above the name and make it bigger.
![image](https://cloud.githubusercontent.com/assets/7809021/23583372/7256039e-00f7-11e7-9eea-cc06771698ed.png)

**Comment by theRonLewis** [comment]
switched both placement, and class (so styling is flipped too). will let others weigh in on if more styling changes should be made before closing. I am avoiding making custom CSS just for this until we decide what else we want to do with style.

![image](https://cloud.githubusercontent.com/assets/6288767/23690068/b64d2cac-0373-11e7-9345-665e2fd1d18a.png)

**Comment by theRonLewis** [comment]
discussed with team, good for now until client asks for additional styling
